apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l4p1h76o4-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l4p1h76o4-go 
  name: l4p1h76o4-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: l4p1h76o4-go 
